### ISSUE TITLE
Use enum for training kind

### ISSUE THREAD

**Issue by jhughes982** [ucl-arc-tre/portal#138]
- At the moment we have this in `api.web.yaml`:

```
TrainingRecord:
      type: object
      required:
        - kind
        - is_valid
      properties:
        kind:
          type: string // this should be an enum
          description: The type of training (e.g., "nhsd")
        is_valid:
          type: boolean
          description: Whether this training certification is currently valid
        completed_at:
          type: string
          description: Time in RFC3339 format when the training was completed
```

- @t-young31 pointed out that it would be better to have the type as an enum which will account for different kinds of training records in the future.

## Definition of done
- [ ] The `TrainingRecord` type is made into an enum rather than a string
